#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
plot_replicated_figures.py

Creates main scenario-comparison figures and summary tables from saved outputs.

This script does not run simulations. It reads the CSV and compact spatial-array
files generated by run_replicated_analysis.py, then creates time-series plots,
last-window distribution plots, final-minus-initial change plots, combined
triptychs and spatial heat maps for the manuscript.

Use --run-group latest to automatically select the newest compatible run group.
"""
from __future__ import annotations

from pathlib import Path
import argparse
import json
import math
import time
from typing import Dict, List, Tuple, Any, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.backends.backend_pdf import PdfPages


# =============================================================================
# Paths and options
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
SRC_ROOT = SCRIPT_DIR.parent
ROOT = SRC_ROOT.parent
RESULTS_DIR = ROOT / "results"
TABLES_DIR = RESULTS_DIR / "tables"
FIGURES_ROOT = RESULTS_DIR / "figures"

LAST_WINDOW = 24
SAVE_FORMATS = ("pdf",)  # add "png" or "svg" if previews are needed
SHOW_TITLES = True
BUILD_INDIVIDUAL_FIGURES = True
BUILD_COMBINED_TRIPTYCH = True
BUILD_DECOMPOSITION_FIGURES = True
BUILD_SENSITIVITY_FIGURES = True
BUILD_K1_SPATIAL_HEATMAPS = True

FIGSIZE_TS = (4.6, 3.35)
FIGSIZE_BOX = (4.1, 3.35)
FIGSIZE_TRIPTYCH = (7.6, 4.85)
FIGSIZE_SENS = (4.8, 3.45)
FIGSIZE_DECOMP = (4.8, 3.45)
FIGSIZE_K1_SPATIAL = (8.4, 7.8)

plt.rcParams.update({
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "font.family": "sans-serif",
    "font.size": 8.5,
    "axes.titlesize": 9.5,
    "axes.labelsize": 8.5,
    "xtick.labelsize": 7.5,
    "ytick.labelsize": 7.5,
    "legend.fontsize": 7.0,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "axes.linewidth": 0.8,
    "lines.linewidth": 1.6,
})

SCENARIO_LABELS = {
    "ce_off": "Linear reference",
    "ce_light": "Light CE",
    "baseline": "Baseline CE",
    "ce_strong": "Targeted CE expansion",
    "ce_inclusive_strong": "Inclusive CE expansion",
}

SCENARIO_LABELS_SHORT = {
    "ce_off": "Linear\nreference",
    "ce_light": "Light\nCE",
    "baseline": "Baseline\nCE",
    "ce_strong": "Targeted CE\nexpansion",
    "ce_inclusive_strong": "Inclusive CE\nexpansion",
}

SCENARIO_COLORS = {
    "ce_off": "black",
    "ce_light": "0.55",
    "baseline": "tab:blue",
    "ce_strong": "tab:orange",
    "ce_inclusive_strong": "tab:red",
}

SCENARIO_ORDER = [
    "ce_off",
    "ce_light",
    "baseline",
    "ce_strong",
    "ce_inclusive_strong",
]

# New metric names with backward compatibility.
METRIC_ALIASES = {
    "MEAN_LOCAL_CE_ACTIVATION": ["MEAN_LOCAL_CE_ACTIVATION", "CE_INTENSITY"],
}


def _ordered_scenarios(keys):
    keys = list(keys)
    ordered = [s for s in SCENARIO_ORDER if s in keys]
    ordered.extend(sorted([s for s in keys if s not in SCENARIO_ORDER]))
    return ordered


# Main metrics. D_labor_income, MEAN_LABOR_INCOME and P_voice_corr are excluded
# from the main figure set to avoid introducing a new zero-inflated K5 issue.
METRICS: List[Tuple[str, str, str]] = [
    ("MEAN_LOCAL_CE_ACTIVATION", "Mean local CE activation", "Mean local CE activation (K1)"),
    ("CEI_SIM", "Flow-based CE index", "Flow-based citywide CE index (K2)"),
    ("CE_MATERIAL_FLOW_NORM", "Normalized material flow", "Normalized CE material flow"),
    ("CE_REPAIR_VISIT_NORM", "Repair visits/household", "Normalized repair activity"),
    ("TRADES_COUNT_M", "Drop-offs/month", "Total recycling/drop-off count"),
    ("TRADES_MASS_M", "Mass/month", "Total recycling/drop-off mass"),
    ("REPAIRS_COUNT_M", "Repair visits/month", "Repair activity"),
    ("SORT_DROPOFF_COUNT_M", "Sorting drop-offs/month", "Sorting drop-off count"),
    ("BULKY_DROPOFF_COUNT_M", "Bulky drop-offs/month", "Bulky-waste drop-off count"),
    ("SORT_DROPOFF_MASS_M", "Sorting mass/month", "Sorting drop-off mass"),
    ("BULKY_DROPOFF_MASS_M", "Bulky mass/month", "Bulky-waste drop-off mass"),
    ("UNEMPLOYMENT", "Unemployment rate", "Unemployment"),
    ("D_adv_exposure", "Advantage-exposure Gini", "Spatial-advantage exposure inequality"),
    ("D_adv_cell", "Cell advantage Gini", "Cell-level spatial-advantage inequality"),
    ("MEAN_ADV_EXPOSURE", "Mean advantage exposure", "Mean spatial-advantage exposure"),
    ("D_resources", "Resource Gini", "Accumulated economic-resource inequality"),
    ("MEAN_RESOURCES", "Mean resources", "Mean accumulated economic resources"),
    ("MOVE_COUNT_M", "Exposure updates/month", "Location/exposure updates"),
    ("MOVE_RATE_M", "Exposure-update share", "Location/exposure update rate"),
    ("N_HOUSEHOLDS", "Households", "Household count"),
    ("MEAN_HOUSEHOLD_SIZE", "Mean household size", "Mean household size"),
    ("TOTAL_SYNTHETIC_POPULATION", "Synthetic population", "Synthetic population"),
    ("HOUSEHOLD_SIZE_CHANGE_COUNT_M", "Size changes/month", "Within-household size changes"),
    ("OBSERVED_CE_ACTIONS_M", "Observed actions/month", "Observed CE actions"),
    ("CE_ACTION_RECOGNITION_OPPORTUNITIES_M", "Recognition opportunities/month", "CE recognition opportunities"),
    ("OBSERVED_CE_ACTION_RATE_M", "Observed-action share", "CE action observability rate"),
    ("R_gap", "Recognition gap", "Recognition inequality"),
]

CORE_KPIS = [
    "MEAN_LOCAL_CE_ACTIVATION", "CEI_SIM", "CE_MATERIAL_FLOW_NORM", "CE_REPAIR_VISIT_NORM",
    "TRADES_COUNT_M", "TRADES_MASS_M", "REPAIRS_COUNT_M", "UNEMPLOYMENT",
    "D_adv_exposure", "D_resources", "MEAN_ADV_EXPOSURE", "MEAN_RESOURCES",
    "MOVE_RATE_M", "MEAN_HOUSEHOLD_SIZE", "TOTAL_SYNTHETIC_POPULATION",
    "OBSERVED_CE_ACTION_RATE_M",
]

COMBINED_METRICS = [
    "MEAN_LOCAL_CE_ACTIVATION", "CEI_SIM", "CE_MATERIAL_FLOW_NORM", "CE_REPAIR_VISIT_NORM",
    "TRADES_COUNT_M", "TRADES_MASS_M", "REPAIRS_COUNT_M", "UNEMPLOYMENT",
    "D_adv_exposure", "D_resources", "MEAN_ADV_EXPOSURE", "MEAN_RESOURCES",
    "MOVE_RATE_M", "OBSERVED_CE_ACTION_RATE_M", "MEAN_HOUSEHOLD_SIZE",
    "TOTAL_SYNTHETIC_POPULATION",
]

BETA_METRICS = [
    ("UNEMPLOYMENT", "Unemployment rate", "Unemployment sensitivity to β_CEI"),
    ("D_resources", "Resource Gini", "Resource inequality sensitivity to β_CEI"),
    ("CEI_SIM", "Flow-based CE index", "Flow-based CE index under β_CEI sensitivity"),
    ("MEAN_LOCAL_CE_ACTIVATION", "Mean local CE activation", "Mean local CE activation under β_CEI sensitivity"),
]

OBS_METRICS = [
    ("OBSERVED_CE_ACTION_RATE_M", "Observed-action share", "Observed CE-action share"),
    ("R_gap", "Recognition gap", "Recognition response"),
    ("CEI_SIM", "Flow-based CE index", "Flow-based CE index under observability sensitivity"),
    ("D_resources", "Resource Gini", "Resource inequality under observability sensitivity"),
    ("D_adv_exposure", "Advantage-exposure Gini", "Spatial-advantage inequality under observability sensitivity"),
]


# =============================================================================
# Helpers
# =============================================================================

def _find_latest_run_group() -> str:
    manifests = sorted(TABLES_DIR.glob("r*_run_manifest.csv"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not manifests:
        raise FileNotFoundError(f"No run manifest found under {TABLES_DIR}")
    return manifests[0].name.replace("_run_manifest.csv", "")


def _manifest_path(run_group: str) -> Path:
    return TABLES_DIR / f"{run_group}_run_manifest.csv"


def _savefig(fig: plt.Figure, out_base: Path) -> None:
    out_base.parent.mkdir(parents=True, exist_ok=True)
    for fmt in SAVE_FORMATS:
        path = out_base.with_suffix(f".{fmt}")
        if fmt.lower() == "png":
            fig.savefig(path, format=fmt, dpi=600, bbox_inches="tight")
        else:
            fig.savefig(path, format=fmt, bbox_inches="tight")


def _read_log(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if "cycle" not in df.columns:
        for cand in ["Cycle", "CYCLE", "t", "month"]:
            if cand in df.columns:
                df = df.rename(columns={cand: "cycle"})
                break
    return df


def _load_experiment(manifest: pd.DataFrame, experiment: str) -> Dict[str, Dict[str, object]]:
    sub = manifest[(manifest["experiment"] == experiment) & (manifest["status"] == "ok")].copy()
    result: Dict[str, Dict[str, object]] = {}
    for scenario, sgrp in sub.groupby("scenario"):
        reps = []
        cycles_ref = None
        meta_rows = []
        for _, row in sgrp.sort_values("replicate").iterrows():
            csv_path = Path(str(row.get("master_csv", "")))
            if not csv_path.exists():
                continue
            df = _read_log(csv_path)
            if "cycle" not in df.columns:
                continue
            cycles = df["cycle"].to_numpy(dtype=float)
            if cycles_ref is None:
                cycles_ref = cycles
            reps.append(df)
            meta_rows.append(row.to_dict())
        if reps and cycles_ref is not None:
            result[scenario] = {"cycles": cycles_ref, "replicates": reps, "meta": meta_rows}
    return result


def _load_sensitivity(manifest: pd.DataFrame, experiment: str, param_col: str) -> Dict[float, Dict[str, Dict[str, object]]]:
    sub = manifest[(manifest["experiment"] == experiment) & (manifest["status"] == "ok")].copy()
    if param_col not in sub.columns:
        return {}
    sub[param_col] = pd.to_numeric(sub[param_col], errors="coerce")
    result: Dict[float, Dict[str, Dict[str, object]]] = {}
    for param_value, pgrp in sub.groupby(param_col):
        scen_payload: Dict[str, Dict[str, object]] = {}
        for scenario, sgrp in pgrp.groupby("scenario"):
            reps = []
            cycles_ref = None
            for _, row in sgrp.sort_values("replicate").iterrows():
                csv_path = Path(str(row.get("master_csv", "")))
                if not csv_path.exists():
                    continue
                df = _read_log(csv_path)
                if "cycle" not in df.columns:
                    continue
                cycles = df["cycle"].to_numpy(dtype=float)
                if cycles_ref is None:
                    cycles_ref = cycles
                reps.append(df)
            if reps and cycles_ref is not None:
                scen_payload[scenario] = {"cycles": cycles_ref, "replicates": reps, param_col: float(param_value)}
        if scen_payload:
            result[float(param_value)] = scen_payload
    return result


def _column_for_metric(df: pd.DataFrame, metric: str) -> Optional[str]:
    for cand in METRIC_ALIASES.get(metric, [metric]):
        if cand in df.columns:
            return cand
    return None


def _stack_metric(payload: Dict[str, object], metric: str) -> Tuple[np.ndarray, np.ndarray]:
    cycles = np.asarray(payload["cycles"], dtype=float)
    reps: List[pd.DataFrame] = payload["replicates"]  # type: ignore
    series = []
    for df in reps:
        col = _column_for_metric(df, metric)
        if col is None:
            series.append(np.full(len(cycles), np.nan, dtype=float))
        else:
            arr = df[col].to_numpy(dtype=float)
            out = np.full(len(cycles), np.nan, dtype=float)
            m = min(len(cycles), len(arr))
            out[:m] = arr[:m]
            series.append(out)
    return cycles, np.vstack(series)


def _mean_ci(arr: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    mean = np.nanmean(arr, axis=0)
    n_eff = np.sum(np.isfinite(arr), axis=0)
    std = np.nanstd(arr, axis=0, ddof=1)
    hw = np.zeros_like(mean, dtype=float)
    valid = n_eff > 1
    hw[valid] = 1.96 * std[valid] / np.sqrt(n_eff[valid])
    return mean, mean - hw, mean + hw


def _last_values(arr: np.ndarray, window: int = LAST_WINDOW) -> np.ndarray:
    w = min(window, arr.shape[1])
    vals = np.nanmean(arr[:, -w:], axis=1)
    return vals[np.isfinite(vals)]


def _delta_values(arr: np.ndarray) -> np.ndarray:
    vals = arr[:, -1] - arr[:, 0]
    return vals[np.isfinite(vals)]


def _summ(vals: np.ndarray) -> Dict[str, float]:
    vals = vals[np.isfinite(vals)]
    n = vals.size
    if n == 0:
        return {"n": 0, "mean": np.nan, "sd": np.nan, "ci_low": np.nan, "ci_high": np.nan, "median": np.nan, "min": np.nan, "max": np.nan}
    mean = float(np.mean(vals))
    sd = float(np.std(vals, ddof=1)) if n > 1 else 0.0
    hw = 1.96 * sd / math.sqrt(n) if n > 1 else 0.0
    return {"n": int(n), "mean": mean, "sd": sd, "ci_low": mean - hw, "ci_high": mean + hw, "median": float(np.median(vals)), "min": float(np.min(vals)), "max": float(np.max(vals))}


def _metric_lookup(metric: str) -> Tuple[str, str]:
    for m, y, title in METRICS:
        if m == metric:
            return y, title
    return metric, metric


def _format_axes(ax: plt.Axes) -> None:
    ax.tick_params(axis="both", which="major", length=3.0, width=0.8)
    for spine in ax.spines.values():
        spine.set_linewidth(0.8)


def _style_categorical_axis(ax: plt.Axes, labels: List[str], *, rotation: float = 0.0, fontsize: float = 7.0) -> None:
    positions = np.arange(1, len(labels) + 1)
    ax.set_xticks(positions)
    ax.set_xticklabels(labels, rotation=rotation, ha="center", linespacing=0.9)
    ax.tick_params(axis="x", labelsize=fontsize, pad=2)
    ax.margins(x=0.06)


def _apply_boxplot_style(bp: Dict[str, Any], colors: List[str], *, alpha: float = 0.55, lw: float = 0.9) -> None:
    for box, color in zip(bp["boxes"], colors):
        box.set_facecolor(color)
        box.set_alpha(alpha)
        box.set_linewidth(lw)
    for whisker in bp.get("whiskers", []):
        whisker.set_linewidth(0.85)
    for cap in bp.get("caps", []):
        cap.set_linewidth(0.85)


def _add_title(ax: plt.Axes, title: str) -> None:
    if SHOW_TITLES:
        ax.set_title(title, pad=6)


def _legend_below(fig: plt.Figure, handles, labels, ncol: int = 2, bottom: float = 0.28) -> None:
    fig.legend(handles, labels, loc="lower center", bbox_to_anchor=(0.5, 0.01), ncol=ncol, frameon=True)
    fig.subplots_adjust(bottom=bottom)


# =============================================================================
# Tables
# =============================================================================

def write_summary_tables(main: Dict[str, Dict[str, object]], run_group: str) -> None:
    rows = []
    for metric, _, _ in METRICS:
        for scenario in _ordered_scenarios(main.keys()):
            payload = main[scenario]
            _, arr = _stack_metric(payload, metric)
            if np.all(~np.isfinite(arr)):
                continue
            last = _summ(_last_values(arr))
            delta = _summ(_delta_values(arr))
            rows.append({
                "metric": metric,
                "scenario": scenario,
                "scenario_label": SCENARIO_LABELS.get(scenario, scenario),
                "n_runs": last["n"],
                "last_window": LAST_WINDOW,
                "last_mean": last["mean"],
                "last_sd": last["sd"],
                "last_ci95_low": last["ci_low"],
                "last_ci95_high": last["ci_high"],
                "last_median": last["median"],
                "last_min": last["min"],
                "last_max": last["max"],
                "delta_convention": "final_minus_initial",
                "delta_mean": delta["mean"],
                "delta_sd": delta["sd"],
                "delta_ci95_low": delta["ci_low"],
                "delta_ci95_high": delta["ci_high"],
                "delta_median": delta["median"],
                "delta_min": delta["min"],
                "delta_max": delta["max"],
            })
    pd.DataFrame(rows).to_csv(TABLES_DIR / f"{run_group}_metric_summary_last{LAST_WINDOW}_and_delta.csv", index=False)
    core_rows = [r for r in rows if r["metric"] in CORE_KPIS]
    pd.DataFrame(core_rows).to_csv(TABLES_DIR / f"{run_group}_core_kpi_summary.csv", index=False)


# =============================================================================
# Main figures
# =============================================================================

def plot_metric_individual(main: Dict[str, Dict[str, object]], metric: str, y_label: str, title: str, out_dir: Path) -> None:
    data = {}
    for scenario in _ordered_scenarios(main.keys()):
        payload = main[scenario]
        cycles, arr = _stack_metric(payload, metric)
        if np.all(~np.isfinite(arr)):
            continue
        data[scenario] = (cycles, arr)
    if not data:
        return

    fig, ax = plt.subplots(figsize=FIGSIZE_TS)
    handles, labels = [], []
    for scenario in _ordered_scenarios(data.keys()):
        cycles, arr = data[scenario]
        mean, lower, upper = _mean_ci(arr)
        color = SCENARIO_COLORS.get(scenario, "black")
        line, = ax.plot(cycles, mean, color=color, label=SCENARIO_LABELS.get(scenario, scenario))
        ax.fill_between(cycles, lower, upper, color=color, alpha=0.18, linewidth=0)
        handles.append(line)
        labels.append(SCENARIO_LABELS.get(scenario, scenario))
    _add_title(ax, title)
    ax.set_xlabel("Month")
    ax.set_ylabel(y_label)
    _format_axes(ax)
    _legend_below(fig, handles, labels, ncol=2, bottom=0.30)
    _savefig(fig, out_dir / f"{metric}_mean_CI")
    plt.close(fig)

    vals, labels_box, colors = [], [], []
    for scenario in _ordered_scenarios(data.keys()):
        _, arr = data[scenario]
        v = _last_values(arr)
        if v.size:
            vals.append(v)
            labels_box.append(SCENARIO_LABELS_SHORT.get(scenario, scenario))
            colors.append(SCENARIO_COLORS.get(scenario, "0.5"))
    if vals:
        fig, ax = plt.subplots(figsize=FIGSIZE_BOX)
        bp = ax.boxplot(vals, patch_artist=True, showmeans=True,
                        medianprops={"color": "black", "linewidth": 1.2},
                        meanprops={"marker": "o", "markerfacecolor": "white", "markeredgecolor": "black", "markersize": 4})
        _apply_boxplot_style(bp, colors, alpha=0.55, lw=0.9)
        _style_categorical_axis(ax, labels_box, fontsize=7.0)
        _add_title(ax, f"{title}: last {LAST_WINDOW} months")
        ax.set_ylabel(y_label)
        _format_axes(ax)
        fig.tight_layout(pad=0.8)
        _savefig(fig, out_dir / f"{metric}_box_last{LAST_WINDOW}")
        plt.close(fig)

    vals, labels_box, colors = [], [], []
    for scenario in _ordered_scenarios(data.keys()):
        _, arr = data[scenario]
        v = _delta_values(arr)
        if v.size:
            vals.append(v)
            labels_box.append(SCENARIO_LABELS_SHORT.get(scenario, scenario))
            colors.append(SCENARIO_COLORS.get(scenario, "0.5"))
    if vals:
        fig, ax = plt.subplots(figsize=FIGSIZE_BOX)
        bp = ax.boxplot(vals, patch_artist=True, showmeans=True,
                        medianprops={"color": "black", "linewidth": 1.2},
                        meanprops={"marker": "o", "markerfacecolor": "white", "markeredgecolor": "black", "markersize": 4})
        _apply_boxplot_style(bp, colors, alpha=0.55, lw=0.9)
        _style_categorical_axis(ax, labels_box, fontsize=7.0)
        _add_title(ax, f"{title}: change")
        ax.set_ylabel(r"Change ($M_T-M_0$)")
        _format_axes(ax)
        fig.tight_layout(pad=0.8)
        _savefig(fig, out_dir / f"{metric}_box_delta")
        plt.close(fig)


def plot_triptych(main: Dict[str, Dict[str, object]], metric: str, out_dir: Path) -> None:
    y_label, title = _metric_lookup(metric)
    data = {}
    for scenario in _ordered_scenarios(main.keys()):
        payload = main[scenario]
        cycles, arr = _stack_metric(payload, metric)
        if np.all(~np.isfinite(arr)):
            continue
        data[scenario] = (cycles, arr)
    if not data:
        return

    fig = plt.figure(figsize=FIGSIZE_TRIPTYCH)
    gs = fig.add_gridspec(2, 2, width_ratios=[1.35, 1.0], height_ratios=[1, 1])
    ax_ts = fig.add_subplot(gs[:, 0])
    ax_last = fig.add_subplot(gs[0, 1])
    ax_delta = fig.add_subplot(gs[1, 1])

    handles, labels = [], []
    for scenario in _ordered_scenarios(data.keys()):
        cycles, arr = data[scenario]
        mean, lower, upper = _mean_ci(arr)
        color = SCENARIO_COLORS.get(scenario, "black")
        line, = ax_ts.plot(cycles, mean, color=color)
        ax_ts.fill_between(cycles, lower, upper, color=color, alpha=0.16, linewidth=0)
        handles.append(line)
        labels.append(SCENARIO_LABELS.get(scenario, scenario))
    ax_ts.set_title("(a) Mean ± 95% CI", pad=6, fontweight="bold")
    ax_ts.set_xlabel("Month")
    ax_ts.set_ylabel(y_label)
    _format_axes(ax_ts)

    vals, labels_box, colors = [], [], []
    for scenario in _ordered_scenarios(data.keys()):
        _, arr = data[scenario]
        v = _last_values(arr)
        if v.size:
            vals.append(v)
            labels_box.append(SCENARIO_LABELS_SHORT.get(scenario, scenario))
            colors.append(SCENARIO_COLORS.get(scenario, "0.5"))
    if vals:
        bp = ax_last.boxplot(vals, patch_artist=True, showmeans=True,
                             medianprops={"color": "black", "linewidth": 1.0},
                             meanprops={"marker": "o", "markerfacecolor": "white", "markeredgecolor": "black", "markersize": 3.5})
        _apply_boxplot_style(bp, colors, alpha=0.55, lw=0.8)
        _style_categorical_axis(ax_last, labels_box, fontsize=6.8)
    ax_last.set_title(f"(b) Last {LAST_WINDOW} months", pad=6, fontweight="bold")
    ax_last.set_ylabel(y_label)
    _format_axes(ax_last)

    vals, labels_box, colors = [], [], []
    for scenario in _ordered_scenarios(data.keys()):
        _, arr = data[scenario]
        v = _delta_values(arr)
        if v.size:
            vals.append(v)
            labels_box.append(SCENARIO_LABELS_SHORT.get(scenario, scenario))
            colors.append(SCENARIO_COLORS.get(scenario, "0.5"))
    if vals:
        bp = ax_delta.boxplot(vals, patch_artist=True, showmeans=True,
                              medianprops={"color": "black", "linewidth": 1.0},
                              meanprops={"marker": "o", "markerfacecolor": "white", "markeredgecolor": "black", "markersize": 3.5})
        _apply_boxplot_style(bp, colors, alpha=0.55, lw=0.8)
        _style_categorical_axis(ax_delta, labels_box, fontsize=6.8)
    ax_delta.set_title("(c) Change", pad=6, fontweight="bold")
    ax_delta.set_ylabel(r"Change ($M_T-M_0$)")
    _format_axes(ax_delta)

    if SHOW_TITLES:
        fig.suptitle(title, y=0.985, fontsize=11.5)
    fig.legend(handles, labels, loc="upper center", bbox_to_anchor=(0.5, 0.93),
               ncol=2, frameon=True, columnspacing=1.4, handlelength=2.4)
    fig.subplots_adjust(left=0.08, right=0.985, top=0.76, bottom=0.10,
                        wspace=0.28, hspace=0.44)
    _savefig(fig, out_dir / f"COMBINED_{metric}_triptych")
    plt.close(fig)


def plot_flow_decomposition(main: Dict[str, Dict[str, object]], out_dir: Path) -> None:
    components_count = [
        ("SORT_DROPOFF_COUNT_M", "Sorting", "tab:blue"),
        ("BULKY_DROPOFF_COUNT_M", "Bulky", "tab:orange"),
        ("REPAIRS_COUNT_M", "Repair", "tab:green"),
    ]
    components_mass = [
        ("SORT_DROPOFF_MASS_M", "Sorting", "tab:blue"),
        ("BULKY_DROPOFF_MASS_M", "Bulky", "tab:orange"),
    ]

    for scenario in _ordered_scenarios(main.keys()):
        payload = main[scenario]
        for kind, comps, ylabel in [
            ("counts", components_count, "Monthly count"),
            ("mass", components_mass, "Monthly mass"),
        ]:
            fig, ax = plt.subplots(figsize=FIGSIZE_DECOMP)
            handles, labels = [], []
            any_plotted = False
            for metric, label, color in comps:
                cycles, arr = _stack_metric(payload, metric)
                if np.all(~np.isfinite(arr)):
                    continue
                mean, lower, upper = _mean_ci(arr)
                line, = ax.plot(cycles, mean, color=color, label=label)
                ax.fill_between(cycles, lower, upper, color=color, alpha=0.16, linewidth=0)
                handles.append(line)
                labels.append(label)
                any_plotted = True
            if not any_plotted:
                plt.close(fig)
                continue
            _add_title(ax, f"K3 flow decomposition: {SCENARIO_LABELS.get(scenario, scenario)}")
            ax.set_xlabel("Month")
            ax.set_ylabel(ylabel)
            _format_axes(ax)
            _legend_below(fig, handles, labels, ncol=len(labels), bottom=0.24)
            _savefig(fig, out_dir / f"K3_flow_decomposition_{kind}_{scenario}")
            plt.close(fig)


# =============================================================================
# K1 spatial heat maps
# =============================================================================

def _resolve_k1_npz(row: Dict[str, Any]) -> Optional[Path]:
    val = str(row.get("k1_spatial_npz", "") or "")
    if val and val.lower() != "nan":
        p = Path(val)
        if p.exists():
            return p
    run_dir = Path(str(row.get("run_dir", "") or ""))
    p = run_dir / "K1_spatial_ce_intensity.npz"
    if p.exists():
        return p
    return None


def _load_k1_spatial(main: Dict[str, Dict[str, object]]) -> Dict[str, Dict[str, Any]]:
    result: Dict[str, Dict[str, Any]] = {}
    for scenario, payload in main.items():
        meta_rows: List[Dict[str, Any]] = payload.get("meta", [])  # type: ignore
        last_mean, last_temporal_sd, change, final = [], [], [], []
        infra = None
        files = []
        for row in meta_rows:
            p = _resolve_k1_npz(row)
            if p is None:
                continue
            try:
                z = np.load(p, allow_pickle=True)
                last_mean.append(np.asarray(z["last_window_mean_grid"], dtype=float))
                last_temporal_sd.append(np.asarray(z["last_window_temporal_sd_grid"], dtype=float))
                change.append(np.asarray(z["change_grid"], dtype=float))
                final.append(np.asarray(z["final_grid"], dtype=float))
                if infra is None:
                    infra = {
                        "ptype": np.asarray(z.get("ptype", np.empty((0, 0))), dtype=int),
                        "hub_cells": np.asarray(z.get("hub_cells", np.empty((0, 2))), dtype=int),
                        "waste_cells": np.asarray(z.get("waste_cells", np.empty((0, 2))), dtype=int),
                        "container_cells": np.asarray(z.get("container_cells", np.empty((0, 2))), dtype=int),
                        "recycling_cells": np.asarray(z.get("recycling_cells", np.empty((0, 2))), dtype=int),
                    }
                files.append(str(p))
            except Exception as exc:
                print(f"[WARN] Could not read K1 spatial file {p}: {exc}")
        if last_mean:
            last_mean_stack = np.stack(last_mean, axis=0)
            last_temporal_stack = np.stack(last_temporal_sd, axis=0)
            change_stack = np.stack(change, axis=0)
            final_stack = np.stack(final, axis=0)
            result[scenario] = {
                "last_mean_stack": last_mean_stack,
                "last_temporal_sd_stack": last_temporal_stack,
                "change_stack": change_stack,
                "final_stack": final_stack,
                "last_mean_across_reps": np.nanmean(last_mean_stack, axis=0),
                "last_crossrep_sd": np.nanstd(last_mean_stack, axis=0, ddof=1) if last_mean_stack.shape[0] > 1 else np.zeros_like(last_mean_stack[0]),
                "last_temporal_sd_mean": np.nanmean(last_temporal_stack, axis=0),
                "change_mean": np.nanmean(change_stack, axis=0),
                "final_mean": np.nanmean(final_stack, axis=0),
                "infra": infra,
                "files": files,
                "n_runs": len(files),
            }
    return result


def _grid_limits(grids: List[np.ndarray], *, force_zero: bool = True, upper_percentile: float = 99.0) -> Tuple[float, float]:
    vals = np.concatenate([g[np.isfinite(g)].ravel() for g in grids if np.isfinite(g).any()]) if grids else np.array([])
    if vals.size == 0:
        return 0.0, 1.0
    vmin = 0.0 if force_zero else float(np.nanpercentile(vals, 1.0))
    vmax = float(np.nanpercentile(vals, upper_percentile))
    if not np.isfinite(vmax) or abs(vmax - vmin) < 1e-12:
        vmax = vmin + 1e-6
    return vmin, vmax


def _overlay_infrastructure(ax: plt.Axes, infra: Optional[Dict[str, np.ndarray]]) -> None:
    if not infra:
        return
    for key, marker, size in [
        ("container_cells", "^", 10),
        ("recycling_cells", "D", 9),
        ("hub_cells", "*", 18),
        ("waste_cells", "x", 12),
    ]:
        pts = np.asarray(infra.get(key, np.empty((0, 2))))
        if pts.size == 0:
            continue
        pts = pts.reshape((-1, 2))
        ax.scatter(pts[:, 0], pts[:, 1], marker=marker, s=size, c="black", linewidths=0.45, alpha=0.70, zorder=3)


def _make_k1_spatial_grid_figure(
    spatial: Dict[str, Dict[str, Any]],
    key: str,
    title: str,
    cbar_label: str,
    *,
    cmap: str = "viridis",
) -> Optional[plt.Figure]:
    """Create one four-scenario K1 spatial heat-map figure with a safe layout.

    The earlier implementation used ``fig.colorbar(..., ax=axes)`` and a very
    tight ``suptitle`` area. In LaTeX/PDF viewers this caused the global title,
    panel titles and colorbar to overlap. This version uses GridSpec with a
    dedicated colorbar column and more vertical headroom.
    """
    scenarios = _ordered_scenarios(spatial.keys())
    if not scenarios:
        return None

    grids = [np.asarray(spatial[s][key], dtype=float) for s in scenarios]
    vmin, vmax = _grid_limits(grids, force_zero=True, upper_percentile=99.0)

    n = len(scenarios)
    ncols = min(4, n)
    nrows = int(math.ceil(n / ncols))

    # Wider and taller than the previous version; the extra width is reserved
    # for a dedicated colorbar axis, not taken from the map panels.
    fig_w = 2.85 * ncols + 0.95
    fig_h = 3.45 * nrows + 0.75
    fig = plt.figure(figsize=(fig_w, fig_h))

    gs = fig.add_gridspec(
        nrows=nrows,
        ncols=ncols + 1,
        width_ratios=[1.0] * ncols + [0.060],
        wspace=0.08,
        hspace=0.30,
    )

    axes: List[plt.Axes] = []
    im = None
    for idx, scenario in enumerate(scenarios):
        r = idx // ncols
        c = idx % ncols
        ax = fig.add_subplot(gs[r, c])
        axes.append(ax)

        grid = np.asarray(spatial[scenario][key], dtype=float)
        im = ax.imshow(
            grid.T,
            origin="lower",
            cmap=cmap,
            vmin=vmin,
            vmax=vmax,
            interpolation="nearest",
        )
        _overlay_infrastructure(ax, spatial[scenario].get("infra"))
        ax.set_title(
            f"{SCENARIO_LABELS.get(scenario, scenario)}\n(n={spatial[scenario].get('n_runs', 0)})",
            fontsize=8.2,
            pad=7.0,
        )
        ax.set_xticks([])
        ax.set_yticks([])
        ax.grid(False)
        for spine in ax.spines.values():
            spine.set_linewidth(0.6)

    # Keep empty cells blank when fewer than four scenarios are present.
    for idx in range(n, nrows * ncols):
        ax = fig.add_subplot(gs[idx // ncols, idx % ncols])
        ax.axis("off")

    if im is not None:
        cax = fig.add_subplot(gs[:, -1])
        cbar = fig.colorbar(im, cax=cax)
        cbar.set_label(cbar_label, fontsize=9.2, labelpad=10)
        cbar.ax.tick_params(labelsize=8.2, width=0.7, length=3)

    if SHOW_TITLES:
        fig.suptitle(title, y=0.985, fontsize=10.6, fontweight="bold")

    # One-row spatial figures need substantial space above the map panels for
    # both the global title and the per-scenario titles. This avoids the overlap
    # visible in the previous K1 spatial PDFs.
    if nrows == 1:
        fig.subplots_adjust(left=0.025, right=0.935, top=0.925, bottom=0.070)
    else:
        fig.subplots_adjust(left=0.035, right=0.935, top=0.865, bottom=0.060)

    return fig


def _plot_k1_spatial_grid(
    spatial: Dict[str, Dict[str, Any]],
    key: str,
    title: str,
    cbar_label: str,
    out_base: Path,
    *,
    cmap: str = "viridis",
) -> None:
    fig = _make_k1_spatial_grid_figure(
        spatial,
        key=key,
        title=title,
        cbar_label=cbar_label,
        cmap=cmap,
    )
    if fig is None:
        return
    _savefig(fig, out_base)
    plt.close(fig)


def _save_k1_spatial_pdf_bundle(spatial: Dict[str, Dict[str, Any]], spatial_dir: Path) -> Path:
    """Save the four K1 spatial diagnostics in one multi-page PDF.

    This is useful for Overleaf and review because opening four separate PDFs
    can feel like an animation. The individual PDFs are still saved for direct
    figure inclusion, while this bundle is convenient as an appendix/supplement.
    """
    specs = [
        (
            "last_mean_across_reps",
            f"K1 spatial distribution: last {LAST_WINDOW}-month mean local CE activation",
            "Mean local CE activation",
            "viridis",
        ),
        (
            "last_crossrep_sd",
            f"K1 spatial uncertainty: cross-replication SD of last {LAST_WINDOW}-month mean",
            "Cross-replication SD",
            "magma",
        ),
        (
            "last_temporal_sd_mean",
            f"K1 spatial variability: within-run temporal SD over the last {LAST_WINDOW} months",
            "Temporal SD",
            "magma",
        ),
        (
            "change_mean",
            "K1 spatial change: final minus initial local CE activation",
            "Final-minus-initial change",
            "viridis",
        ),
    ]

    pdf_path = spatial_dir / "K1_spatial_heatmaps_4page.pdf"
    with PdfPages(pdf_path) as pdf:
        for key, title, cbar_label, cmap in specs:
            fig = _make_k1_spatial_grid_figure(
                spatial,
                key=key,
                title=title,
                cbar_label=cbar_label,
                cmap=cmap,
            )
            if fig is None:
                continue
            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)
    return pdf_path


def plot_k1_spatial_heatmaps(main: Dict[str, Dict[str, object]], out_dir: Path, run_group: str) -> None:
    spatial = _load_k1_spatial(main)
    if not spatial:
        print("[WARN] No K1 spatial NPZ files found. Spatial K1 heat maps were not created.")
        return

    spatial_dir = out_dir / "k1_spatial"
    spatial_dir.mkdir(parents=True, exist_ok=True)

    _plot_k1_spatial_grid(
        spatial,
        key="last_mean_across_reps",
        title=f"K1 spatial distribution: last {LAST_WINDOW}-month mean local CE activation",
        cbar_label="Mean local CE activation",
        out_base=spatial_dir / "K1_spatial_last_window_mean",
        cmap="viridis",
    )
    _plot_k1_spatial_grid(
        spatial,
        key="last_crossrep_sd",
        title=f"K1 spatial uncertainty: cross-replication SD of last {LAST_WINDOW}-month mean",
        cbar_label="Cross-replication SD",
        out_base=spatial_dir / "K1_spatial_last_window_crossrep_sd",
        cmap="magma",
    )
    _plot_k1_spatial_grid(
        spatial,
        key="last_temporal_sd_mean",
        title=f"K1 spatial variability: within-run temporal SD over the last {LAST_WINDOW} months",
        cbar_label="Temporal SD",
        out_base=spatial_dir / "K1_spatial_last_window_temporal_sd",
        cmap="magma",
    )
    _plot_k1_spatial_grid(
        spatial,
        key="change_mean",
        title="K1 spatial change: final minus initial local CE activation",
        cbar_label="Final-minus-initial change",
        out_base=spatial_dir / "K1_spatial_final_minus_initial_change",
        cmap="viridis",
    )

    bundle_path = _save_k1_spatial_pdf_bundle(spatial, spatial_dir)
    print(f"[INFO] K1 spatial multi-page PDF saved to: {bundle_path}")

    rows = []
    for scenario, payload in spatial.items():
        g_mean = payload["last_mean_across_reps"]
        g_sd = payload["last_crossrep_sd"]
        g_change = payload["change_mean"]
        rows.append({
            "scenario": scenario,
            "scenario_label": SCENARIO_LABELS.get(scenario, scenario),
            "n_runs_with_spatial_npz": payload.get("n_runs", 0),
            "last_window_cell_mean_mean": float(np.nanmean(g_mean)),
            "last_window_cell_mean_sd": float(np.nanstd(g_mean)),
            "last_window_crossrep_sd_mean": float(np.nanmean(g_sd)),
            "change_cell_mean": float(np.nanmean(g_change)),
            "change_cell_sd": float(np.nanstd(g_change)),
        })
    pd.DataFrame(rows).to_csv(TABLES_DIR / f"{run_group}_k1_spatial_summary.csv", index=False)


# =============================================================================
# Sensitivity figures
# =============================================================================

def plot_param_sensitivity(
    sens: Dict[float, Dict[str, Dict[str, object]]],
    metrics: List[Tuple[str, str, str]],
    param_name: str,
    label_func,
    out_dir: Path,
    prefix: str,
) -> None:
    if not sens:
        return
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for param_value, scenarios in sens.items():
        for scenario, payload in scenarios.items():
            for metric, _, _ in metrics:
                _, arr = _stack_metric(payload, metric)
                if np.all(~np.isfinite(arr)):
                    continue
                last = _summ(_last_values(arr))
                delta = _summ(_delta_values(arr))
                rows.append({
                    param_name: param_value,
                    "scenario": scenario,
                    "scenario_label": SCENARIO_LABELS.get(scenario, scenario),
                    "metric": metric,
                    "last24_mean": last["mean"],
                    "last24_ci95_low": last["ci_low"],
                    "last24_ci95_high": last["ci_high"],
                    "delta_mean": delta["mean"],
                    "delta_ci95_low": delta["ci_low"],
                    "delta_ci95_high": delta["ci_high"],
                })
    pd.DataFrame(rows).to_csv(TABLES_DIR / f"{out_dir.parent.name}_{prefix}_summary.csv", index=False)

    scenarios = _ordered_scenarios({s for _, payload in sens.items() for s in payload.keys()})
    for scenario in scenarios:
        for metric, ylabel, title in metrics:
            fig, ax = plt.subplots(figsize=FIGSIZE_SENS)
            handles, labels = [], []
            any_plotted = False
            for param_value in sorted(sens.keys(), reverse=True):
                if scenario not in sens[param_value]:
                    continue
                payload = sens[param_value][scenario]
                cycles, arr = _stack_metric(payload, metric)
                if np.all(~np.isfinite(arr)):
                    continue
                mean, lower, upper = _mean_ci(arr)
                line, = ax.plot(cycles, mean, label=label_func(param_value))
                ax.fill_between(cycles, lower, upper, alpha=0.13, linewidth=0)
                handles.append(line)
                labels.append(label_func(param_value))
                any_plotted = True
            if not any_plotted:
                plt.close(fig)
                continue
            _add_title(ax, f"{title}\n{SCENARIO_LABELS.get(scenario, scenario)}")
            ax.set_xlabel("Month")
            ax.set_ylabel(ylabel)
            _format_axes(ax)
            _legend_below(fig, handles, labels, ncol=min(3, len(labels)), bottom=0.29)
            short_metric = metric.replace("UNEMPLOYMENT", "UNEMP").replace("MEAN_LOCAL_CE_ACTIVATION", "K1LOCAL").replace("CE_INTENSITY", "CEINT")
            _savefig(fig, out_dir / f"{short_metric}_{prefix}_{scenario}")
            plt.close(fig)


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-group", default="latest", help="Run group ID, e.g. r20260604_163943, or 'latest'.")
    args = parser.parse_args()

    run_group = _find_latest_run_group() if args.run_group == "latest" else args.run_group
    manifest_csv = _manifest_path(run_group)
    if not manifest_csv.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_csv}")

    out_dir = FIGURES_ROOT / run_group
    out_main = out_dir / "main"
    out_beta = out_dir / "beta"
    out_obs = out_dir / "obs"
    out_main.mkdir(parents=True, exist_ok=True)

    print("============================================================")
    print("Building replicated figures")
    print("============================================================")
    print(f"Run group : {run_group}")
    print(f"Manifest  : {manifest_csv}")
    print(f"Figures   : {out_dir}")
    print("============================================================")

    manifest = pd.read_csv(manifest_csv)

    t0 = time.perf_counter()
    main_payload = _load_experiment(manifest, "main")

    if main_payload:
        write_summary_tables(main_payload, run_group)
        if BUILD_INDIVIDUAL_FIGURES:
            for metric, ylabel, title in METRICS:
                plot_metric_individual(main_payload, metric, ylabel, title, out_main)
        if BUILD_COMBINED_TRIPTYCH:
            for metric in COMBINED_METRICS:
                plot_triptych(main_payload, metric, out_main)
        if BUILD_DECOMPOSITION_FIGURES:
            plot_flow_decomposition(main_payload, out_main)
        if BUILD_K1_SPATIAL_HEATMAPS:
            plot_k1_spatial_heatmaps(main_payload, out_main, run_group)

    if BUILD_SENSITIVITY_FIGURES:
        beta_payload = _load_sensitivity(manifest, "beta", "beta_cei")
        plot_param_sensitivity(
            beta_payload,
            BETA_METRICS,
            param_name="beta_cei",
            label_func=lambda v: rf"$\beta_{{CEI}}={v:g}$",
            out_dir=out_beta,
            prefix="beta",
        )

        obs_payload = _load_sensitivity(manifest, "obs", "observability_prob")
        plot_param_sensitivity(
            obs_payload,
            OBS_METRICS,
            param_name="observability_prob",
            label_func=lambda v: rf"$p_{{obs}}={v:g}$",
            out_dir=out_obs,
            prefix="obs",
        )

    duration = time.perf_counter() - t0
    meta = {
        "run_group": run_group,
        "manifest": str(manifest_csv),
        "figures_dir": str(out_dir),
        "last_window": LAST_WINDOW,
        "delta_convention": "final_minus_initial",
        "excluded_main_metrics": ["D_labor_income", "MEAN_LABOR_INCOME", "P_voice_corr"],
        "k1_spatial_heatmaps": bool(BUILD_K1_SPATIAL_HEATMAPS),
        "duration_sec": duration,
    }
    (TABLES_DIR / f"{run_group}_figure_build_meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    print("\n[DONE] Figure build complete.")
    print(f"[DONE] Figures saved under: {out_dir}")
    print(f"[DONE] Summary tables saved under: {TABLES_DIR}")


if __name__ == "__main__":
    main()
